version: "3.8"

services:
  nginx-gateway:
    build:
      context: ./nginx-gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - books
      - customers
      - orders
      - auth-service
    networks:
      - library-network

  books:
    build:
      context: ./books
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
    networks:
      - library-network

  customers:
    build:
      context: ./customers
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
      - PORT=5002
    networks:
      - library-network

  orders:
    build:
      context: ./orders
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - NODE_ENV=production
      - PORT=5003
    networks:
      - library-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    environment:
      - NODE_ENV=production
      - PORT=5004
      - JWT_SECRET=G4heiQGe5XDjL8gxY8iUs9gZe1ilHxK7aG9CsSscgi3gH4jErZvm40ZUBrUFpRSo
    networks:
      - library-network

networks:
  library-network:
    driver: bridge
